swagger: "2.0"
info:
  title: 报警转发器
  description: 转发Alertmanager的webhook信息，到钉钉、微信、或其它客户端
  version: 1.0.0
  termsOfService: https://blog.taycc.com/pages/prometheus/target_icmp.html
  contact:
    email: tay3223@qq.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /alertmanager/dingding/k8s:
    post:
      tags:
      - alertmanager
      description: 推送数据到钉钉，数据来自于Alertmanager的webhook推送
      operationId: K8sControllers.推送数据
      responses:
        "200":
          description: ok
  /alertmanager/dingding/linux:
    post:
      tags:
      - alertmanager
      description: 推送数据到钉钉，数据来自于Alertmanager的webhook推送
      operationId: LinuxControllers.推送数据
      responses:
        "200":
          description: ok
  /test/:
    get:
      tags:
      - test
    post:
      tags:
      - test
  /web/json:
    get:
      tags:
      - web
      description: 推送数据到钉钉，数据来自于Alertmanager的webhook推送
      operationId: JsonControllers.推送数据
      responses:
        "200":
          description: ok
  /web/map:
    get:
      tags:
      - web
    post:
      tags:
      - web
      description: 推送数据到钉钉，数据来自于Alertmanager的webhook推送
      operationId: MapControllers.推送数据
      responses:
        "200":
          description: ok
  /web/template:
    get:
      tags:
      - web
    post:
      tags:
      - web
tags:
- name: alertmanager
  description: |
    接收Alertmanager推送的报警信息
- name: alertmanager
  description: |
    转发来自于Prometheus的数据
